export const GET_COUNTRIES_REQUESTED = 'GET_COUNTRIES_REQUESTED';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAILED = 'GET_COUNTRIES_FAILED';

export const SET_COUNTRY = 'SET_COUNTRY';
export const CLEAR_COUNTRY = 'CLEAR_COUNTRY';
export const GET_COUNTRY_REQUESTED = 'GET_COUNTRY_REQUESTED';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_FAILED = 'GET_COUNTRY_FAILED';

export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const SET_SEARCH_SUGGESTIONS = 'SET_SEARCH_SUGGESTIONS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

